import { prisma } from '../db'
import { computeAdherence } from './adherenceCoach'
import { checkSafety } from './safetyScreening'

export interface PatientReport {
  generatedAt: string
  patient: {
    id: number
    firstName: string
    lastName: string
    email: string
  }
  protocol: {
    daysOnProtocol: number | null
    dietAdherencePercent: number | null
    protocolPhase: string | null
  }
  adherence: {
    currentStreakDays: number
    longestStreakDays: number
    totalDaysLogged: number
    adherencePercent30d: number
    milestones: string[]
  }
  latestBiomarkers: {
    readingAt: string
    bloodGlucoseMgdl: number | null
    betaHydroxybutyrateMmol: number | null
    gkiScore: number | null
    metabolicZone: string | null
    crpMgL: number | null
    altUl: number | null
    astUl: number | null
  } | null
  gkiTrend90d: Array<{ date: string; gki: number; zone: string | null }>
  safetyFlags: {
    hasType1Diabetes: boolean
    hasKidneyDisease: boolean
    hasLiverDisease: boolean
    isPregnant: boolean
    warnings: string[]
  } | null
  disclaimer: string
}

export async function generatePatientReport(patientId: number): Promise<PatientReport> {
  const user = await prisma.user.findUniqueOrThrow({
    where: { id: patientId },
    select: { id: true, firstName: true, lastName: true, email: true },
  })

  const latestAssessment = await prisma.assessment.findFirst({
    where: { userId: patientId },
    orderBy: { assessmentDate: 'desc' },
    select: { daysOnProtocol: true, dietAdherencePercent: true, protocolPhase: true },
  })

  const latestReading = await prisma.biomarkerReading.findFirst({
    where: { userId: patientId },
    orderBy: { readingAt: 'desc' },
    select: {
      readingAt: true, bloodGlucoseMgdl: true, betaHydroxybutyrateMmol: true,
      gkiScore: true, metabolicZone: true, crpMgL: true, altUl: true, astUl: true,
    },
  })

  const trend90 = await prisma.biomarkerReading.findMany({
    where: {
      userId: patientId,
      gkiScore: { not: null },
      readingAt: { gte: new Date(Date.now() - 90 * 86_400_000) },
    },
    select: { readingAt: true, gkiScore: true, metabolicZone: true },
    orderBy: { readingAt: 'asc' },
  })

  const allDates = await prisma.biomarkerReading.findMany({
    where: { userId: patientId, gkiScore: { not: null } },
    select: { readingAt: true },
    orderBy: { readingAt: 'asc' },
  })

  const adherence = computeAdherence(allDates.map(r => r.readingAt))

  const profile = await prisma.profile.findUnique({ where: { userId: patientId } })

  let safetyFlags = null
  if (profile) {
    const safety = checkSafety({
      hasType1Diabetes: profile.hasType1Diabetes,
      hasKidneyDisease: profile.hasKidneyDisease,
      hasLiverDisease: profile.hasLiverDisease,
      isPregnant: profile.isPregnant,
      currentMedications: profile.currentMedications,
    })
    safetyFlags = {
      hasType1Diabetes: profile.hasType1Diabetes,
      hasKidneyDisease: profile.hasKidneyDisease,
      hasLiverDisease: profile.hasLiverDisease,
      isPregnant: profile.isPregnant,
      warnings: safety.warnings,
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    patient: user,
    protocol: {
      daysOnProtocol: latestAssessment?.daysOnProtocol ?? null,
      dietAdherencePercent: latestAssessment?.dietAdherencePercent ?? null,
      protocolPhase: latestAssessment?.protocolPhase ?? null,
    },
    adherence: {
      currentStreakDays: adherence.currentStreakDays,
      longestStreakDays: adherence.longestStreakDays,
      totalDaysLogged: adherence.totalDaysLogged,
      adherencePercent30d: adherence.adherencePercent,
      milestones: adherence.reachedMilestones.map(m => m.label),
    },
    latestBiomarkers: latestReading
      ? { ...latestReading, readingAt: latestReading.readingAt.toISOString(), metabolicZone: latestReading.metabolicZone ?? null }
      : null,
    gkiTrend90d: trend90.map(r => ({
      date: r.readingAt.toISOString().slice(0, 10),
      gki: r.gkiScore!,
      zone: r.metabolicZone ?? null,
    })),
    safetyFlags,
    disclaimer: 'This report is generated by the MMR application for informational purposes only. It does not replace clinical evaluation. All values should be interpreted in the context of a full clinical assessment.',
  }
}
